- src/library/DIPS.Mobile.UI.Droid/DUI.cs
- src/library/DIPS.Mobile.UI.Droid/Resources/values/styles.xml
- src/library/DIPS.Mobile.UI.Droid/Resources/values/themes.xml
- src/library/DIPS.Mobile.UI.iOS/Components/BottomSheets/BottomSheetContentPage.cs
- src/library/DIPS.Mobile.UI.iOS/DUI.cs
- Made sure bottom sheet content is padded a bit further down on iOS
- Made sure dark mode is disabled for Android
- Made sure material design dialogs are correctly styled when using negative buttons on Android.
> General improvements.

- CHANGELOG.md
- src/app/Components/MainPage.cs
- src/library/DIPS.Mobile.UI/API/Library/DUI.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetService.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheetService.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/HorizontalInlineDatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
- [BreakingChange] Changed the animated flag for closing bottom sheets from bottom sheet service from default:false to true.
- Fixed an issue where HorizontalInlineDatePicker did not set a colors for the date that it started with.
- Fixed an issue where item picker bottom sheet mode did not close the bottom sheet.
- Fixed an issue where setting animated flag when closing bottom sheet did not do anything for Android.
- [ComponentsApp] Added version number to the first pages title.
> Fixes to bottom sheet closing, horizontal in line date picker and added version number to components app

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchEffectTapGestureRecognizer.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs
- [iOS] Fixed an issue where touch effect would still be imminent when a user taps and then slides the finger out of bounds
- [Android] Fixed an issue where touch effect would go out of bounds on some elements
> Fixed issues related to dui:Touch

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Builder/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/Effects/Modal/Android/ModalPlatformEffect.cs
-Made sure modal effect on Android to add navbar does not use a vertical stack layout because it will break collection view scrolling on Android.
> Made sure modal effect on Android to add navbar does not use a vertical stack layout because it will break collection view scrolling on Android.

- CHANGELOG.md
- src/app/Components/MainPage.cs
- src/app/Components/MauiProgram.cs
- src/app/Playground/MauiProgram.cs
- src/library/DIPS.Mobile.UI/API/Builder/Android/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/API/Builder/iOS/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetService.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetContentPage.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetService.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- src/library/DIPS.Mobile.UI/Components/Lists/CollectionView.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Lists/CollectionView.cs
- [ListItem] Added font attributes for title and subtitle.
- [BottomSheet] Made sure Android and iOS bottom sheets are always closed from RemoveViewsLocatedOnTopOfPage().
- [BottomSheet] Made sure Android bottom sheet service returns a task that waits until the fragment is dismissed for consumers to rely on the task from closing methods.
- [CollectionView] Made sure we add additional space at the end of the list (footer) so the last item is always visible. 1/3 of the visible list will be added as a invisible footer so people can easily see and tap the last item.
> Several improvements to ListItem, BottomSheet and CollectionView

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
- Added ShouldDelay property to SearchPage for enabling a small delay before search is invoked
- Added Delay property for defining delay in milliseconds (default = 500)
- Added SearchMode property for disabling automatic search triggering on search text changed
> Added delay and search mode to search page

- CHANGELOG.md
- src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- Fixed an issue where dividers was using extra space on iOS.
- Background color can now be set on list item.
> ListItem fixes

- CHANGELOG.md
- src/app/Components/ResourcesSamples/Icons/IconsSamples.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/HåvardSamples/HåvardPageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Content/ContentControl.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/IListItemOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Icon/IconOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/InLineContent/InLineContentOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/ListItemOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.cs
Fixed an issue when using bindings to control the options did not work due to to the options not having its binding context set.
- [ContentControl][iOS] If content is CollectionView we wrap it in a grid with row=auto.
- [ListItem] Options now inherit the BindingContext of the ListItem.
> Made sure ListItem options inherit the BindingContext of ListItem

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Alerting/SystemMessage/Android/SystemMessageService.cs
- src/library/DIPS.Mobile.UI/Extensions/Android/FragmentManagerExtensions.cs
- [Android] Made sure we safely commit the fragmentmanager when the state was lost to prevent app crashes.
> Made sure we safely commit the fragmentmanager when the state was lost to prevent app crashes.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Searching/SearchBarSamples.xaml
- src/app/Components/ComponentsSamples/Searching/SearchPageSamples.xaml
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs
- src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
- src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
- src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs
- [SearchBar] Added ClearCommand as a command to execute when people tap the clear button (x mark).
- [SearchPage] Make sure clear the text and state of the view when people tap the clear button.
> Made sure SearchPage clears the search text when people tap the X

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Navigation/FloatingNavigationButtonSamples.xaml.cs
- src/app/Components/ComponentsSamples/Navigation/FloatingNavigationButtonSamplesViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/ExtendedNavigationMenuButton/ExtendedNavigationMenuButton.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonConfigurator.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonService.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/IFloatingNavigationButtonConfigurator.cs
- [FloatingNavigationButton] Added option to add a navigation button as the last button. This will be respected if a new button is added after the button was added.
> Added option to add a navigation button as the last button. This will be respected if a new button is added after the button was added.

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/API/Builder/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/API/Builder/iOS/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/Components/Layout/LayoutHandler.cs
- src/library/DIPS.Mobile.UI/Components/Layout/iOS/LayoutHandler.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/Android/FloatingNavigationButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/Android/FloatingNavigationButtonMenuFragment.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/ExtendedNavigationMenuButton/ExtendedNavigationMenuButton.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/NavigationMenuButton/NavigationMenuButton.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/dotnet/FloatingNavigationButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/iOS/FloatingNavigationButtonHandler.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
- src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.nb.resx
- src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx
- src/library/DIPS.Mobile.UI/Resources/Styles/Styles.cs
- src/library/DIPS.Mobile.UI/Resources/Styles/StylesExtension.cs
- [Layout] Made sure all layouts ignore safe area when its not set by the consumer. Grid, StackLayout etc.
- [FloatingNavigationButton] Made sure people can tap the background of the FAB to close it.
- [FloatingNavigationButton] Made sure sizes of the icons are smaller for better UX.
> Safe Area and FloatingNavigationButton improvements.

- CHANGELOG.md
- src/app/Components/Components.csproj
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs
… you opened the Floating Navigation on iOS.
Fixed an bug where the entire page of the app was not clickable until you opened the Floating Navigation on iOS.
> Non clickthrough on iOS floating navigation button

- CHANGELOG.md
- README.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetContentPage.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/iOS/DUIDatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Slidable/SlidableLayout.cs
- src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj
The bug has been introduced when we changed Chip from having default properties to using styles. iOS UIDatePicker was using the Chip ColorProperty default color, which made sense before styles, but not now as we are supporting styles.
> Made sure iOS Date/AndTimePicker use the correct default colors

- CHANGELOG.md
- src/app/Components/Components.csproj
- src/app/Components/ResourcesSamples/Animations/AnimationsSamples.xaml.cs
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/ImageButton.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/CheckmarkListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/NavigationListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/RadioButtonListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/InLineContent/InLineContentOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.cs
- [ListItem] Title will wrap better for consumers.
- [ListItem][TitleOptions] Added ability to control `LineBreakMode` and `MaxLines` to support truncation and wrapping properly.
- [ListItem] Made sure width options are set even if the corresponding view for the options is not set.
- [ComponentsApp] Made sure `none` is not added to animations page.
> [ListItem] Fixes to Title and InLineContent width and added new properties to control truncation/wrapping of title

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/InLineContent/InLineContentOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.cs
- [ListItem] Margin and Paddings are now set on the underlying Border to prevent glitching placements of the containers contet.
- [ListItem] The built in Padding was changed to Margin to prevent the in line content from moving when the title is about to wrap.
- 
Made sure ListItem in line content never moves
> Made sure ListItem in line content never moves

- CHANGELOG.md
- src/app/Components/ComponentsSamples/BottomSheets/Sheets/BottomSheetWithToolbar.xaml
- src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetContentPage.cs
> Fix BottomSheet.ShouldFitToContent not working when Title is set

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs
> Fix not being able to set LoadableListItem.ContextMenu on iOS

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/TextFields/Editor/Android/EditorHandler.cs
- src/library/DIPS.Mobile.UI/Components/TextFields/Entry/Android/EntryHandler.cs
> [Android] Fixed a regression bug where the cursor would not be set at the end of the text when focusing Editor

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetleTestPage1.xaml
- src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs
> SaveView will now only vibrate on success when user actually taps the SaveView

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/Lists/ScrollView/ScrollView.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Lists/ScrollView/ScrollView.cs
- src/library/DIPS.Mobile.UI/Components/Lists/ScrollView/iOS/ScrollViewHandler.cs
- [ScrollView] Added additional space at the bottom of scroll view to make sure the last item is scrolled to approx half the size of the scrollview for better UX.
> Added extra space at bottom of scroll view

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
- [BottomSheet][Android] Made sure consumers do not need to set the text of a toolbar item to add the toolbar item on Android.
> Made toolbar item text nullable on Android for BottomSheet

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
- [BottomSheet] Made sure `Title` is visible for Android.
> [BottomSheet] Made sure `Title` is visible for Android.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.LongPressed.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
> [iOS] Fixed an issue where releasing the long-press context menu interaction too early would fire off the tap event.

- CHANGELOG.md
- src/app/Playground/AppShell.xaml
- src/app/Playground/EirikSamples/EirikPage.xaml
- src/app/Playground/EirikSamples/EirikPage.xaml.cs
- src/app/Playground/EirikSamples/EirikPageViewModel.cs
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/Slidable/SlidableLayout.cs
Fixed a bug where you couldn't tap the next element (only the previous) in a slidable layout
> [SlidableLayout] Fixed a bug where you couldn't tap the next element (only the previous) in a slidable layout

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/DateTimeView.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/DateView.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/DateViewBase.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/HorizontalInlineDatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Slidable/SlidableContentLayout.cs
- src/library/DIPS.Mobile.UI/Components/Slidable/SlidableLayout.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Slidable/SlidableLayout.cs
> DateViewBase and its inheritors now changes its view based on the device orientation, bugfixes in HorizontalInlineDatePicker  

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Labels/Android/MauiTextView.cs
> Fixed an issue where Label would crash application if Text was not set.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Loading/StateView/EmptyView.cs
- src/library/DIPS.Mobile.UI/Components/Loading/StateView/ErrorView.cs
> Fixed an issue where title and description on EmptyView and ErrorView were not horizontally aligned

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateView.cs
> [StateView] Fixed an issue where RefreshCommand would get executed several times when consumer enabling RefreshView for default implementations.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.Properties.cs
> Set default `MaxLines` and `LineBreakMode` for subtitle on `ListItem`.

- CHANGELOG.md
- src/app/Playground/MainPage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs
> Fixed an issue where the label inside `SaveView` would take up space when text empty.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Shell/Android/ShellRenderer.cs
> [Android] Fixed an issue where application would crash if the `ShellToolbarAppearanceTracker` disposed itself before setting appearance

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.cs
> Make event for context menu item clicked be triggered before the command

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/Images/Image/iOS/ImageHandler.cs
- We've observed cases where the image is redrawn, and the tint is not completely cleared after some time. To guard against this crash we've moved the null-check when setting tint color to after the image is ready.
> [Image][iOS] Made sure we do nessesary null-check when the image is ready.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/BarcodeScanning/BarcodeScanningSample.xaml.cs
- src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/BarcodeScanner.cs
- src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/iOS/BarcodeScanner.cs
- src/library/DIPS.Mobile.UI/API/Camera/iOS/PreviewHandler.cs
We've noticed that the barcode scanner for iOS was unstable after a random amount of time when using it. This seem to be solved by not starting and stopping the capturing in between scans. This is not something the component is doing internally, but something the consumer is doing. To test this, the components app are not stopping and starting the capture session in between results.
We've also improved the rect of interest using the same algorithm that Apple is using. This makes the recommended zoom factor act differently, which results in better stability the first time people starts the scanning.
- Improved rect of interest
- Imroved zoom factor
- Made sure the components app does not stop and start between results, this makes it more stable on iOS.
> Improved barcode scanner on iOS

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs
TaskCompletionSource was being set before bottom sheet was removed from stack, causing it not to be "as async as intended"
> [Android] Made sure the CloseAll-task is completed after the stack has been modified and not before

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Pickers/ScrollPickerComponents/DayScrollPickerComponent.cs
- src/app/Components/ComponentsSamples/Pickers/ScrollPickerComponents/MonthScrollPickerComponent.cs
- src/app/Components/ComponentsSamples/Pickers/ScrollPickerComponents/YearScrollPickerComponent.cs
- src/app/Components/ComponentsSamples/Pickers/ScrollPickerSamplesViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/Android/MaterialScrollPickerFragment.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/Android/ScrollPickerHandler.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/IScrollPickerViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/ScrollPickerViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/iOS/ScrollPickerHandler.cs
> [ScrollPicker][BreakingChange] Added `OnDataInvalidated`, to force the UI to update itself. Added a BaseScrollPickerComponent.

- build/BuildSystem/Git.csx
- build/build.csx
Changed buildscript so that nuget packages does not get published as pre-release package when suffix of branch starts with "patch".
> Changed buildscript

- build/BuildSystem/Git.csx
- build/build.csx
Changed buildscript so that nuget packages does not get published as pre-release package when suffix of branch starts with "patch".
> Changed build script

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableDateAndTimePicker/NullableDateAndTimePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableDatePicker/NullableDatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableTimePicker/NullableTimePicker.cs
> [NullableDatePicker] Fixed an issue where if dates were set as default, the pickers would still be null.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.cs
- src/library/DIPS.Mobile.UI/Components/VirtualListView/Android/RvScrollListener.cs
Noticed that setting FormattedText on Title and Subtitle did not work unless you set something on Title and Subtitle. Now, you don't have do to that. There was also an issue where setting an empty Subtitle would take up space on Android.
For VirtualListView, I noticed that the OnScrolled event were invoked every time something is drawn on it. For example, GlobalHeader, footer etc. So now I do a check where it will only call it if the user has previously scrolled.
> More ListItem and VirtualListView bugfixes 

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPicker.cs
Changed control flow of item selection, so that the operation does not immediately return if the list of selected items is empty.
> Fixed an issue where `MultiItemsPicker.DidSelectItem` was not triggered when selecting first item

- CHANGELOG.md
- src/app/Components/App.xaml.cs
- src/app/Components/ResourcesSamples/Icons/IconsSamples.xaml.cs
- src/library/DIPS.Mobile.UI/Resources/Icons/IconResources.cs
- src/library/DIPS.Mobile.UI/Resources/Icons/Icons.cs
To prevent memory leaks when using our Icons api, we've changed the return type from ImageSource to string.
> Changed Icons from ImageSource to string

- CHANGELOG.md
- src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml.cs
- src/library/DIPS.Mobile.UI/Components/Alerting/SystemMessage/SystemMessageConfigurator.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Loading/StateView/EmptyViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Loading/StateView/ErrorViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/ExtendedNavigationMenuButton/ExtendedNavigationMenuButton.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/NavigationMenuButton/NavigationMenuButton.Properties.cs
- src/library/DIPS.Mobile.UI/Resources/Icons/Icons.cs
Made sure all public image sources has a image source converter so the component do not freeze up on Android when passing strings.
> Made sure all public image sources has a image source converter so the component do not freeze up on Android when passing strings.

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/Shell/Android/ShellRenderer.cs
- [ContextMenuToolbarItem][Android] Made sure menu listeners are re-added when a modal page has been popped.
- [ContextMenuToolbarItem][Android] Made sure it does not memoery leak.
> ContextMenuToolbarItem memory leak and modal bug fixes

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Shell/Shell.cs
This could happen if you navigate back and forth, because the call to resolve is awaited, the current page can be changed while the app is in the while loop. With this fix, the "current page" will stay the same
> Fixed an issue where the app could crash when navigating back and forth if the automatic memory resolving were activated.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Chips/ChipsSamples.xaml
- src/app/Components/ComponentsSamples/Chips/ChipsSamplesViewModel.cs
- src/library/DIPS.Mobile.UI/Components/ChipGroup/ChipGroup.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Android/ChipHandler.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Android/OnToggledChangedListener.cs
Sometimes the checkmark were not visible, or the checkmark were of black color. This was due to the TitleColor was set to black when the Chip was initialized, now we update the checkmark color when the Chip is toggled.
Furthermore, when ChipGroup was set to multiple mode, the chips were not able to be un-toggled. This was because we added duplicate objects to the SelectedItems. There is now an if-check in place to make sure this does not happen.
> Fixed two bugs in Chip and ChipGroup

- CHANGELOG.md
- src/app/Components/ComponentsSamples/BottomSheets/BottomSheetSamples.xaml
- src/app/Components/ComponentsSamples/BottomSheets/Sheets/BottomSheetWithBottomBar.xaml
- src/app/Components/ComponentsSamples/BottomSheets/Sheets/BottomSheetWithBottomBar.xaml.cs
- src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
- src/app/Components/Resources/LocalizedStrings/LocalizedStrings.en.resx
- src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
- src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
It seems that MAUI has updated where Grid does not start with Grid.ColumnDefinitions 1, but with 0. Idk
> [BottomSheet] Fixed an issue where app would crash if attempting to create a bottom bar in bottom sheet.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/MemoryManagement/GCCollectionMonitor.cs
Even though the page does not have memory leak, does not mean we should cancel the GC collection. I found that in some pages the viewmodel needed more collections to be GC'ed.
> [MemoryLeak] Always wait for 9 GC collections before checking if there is any memory leaks.

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/Shell/Shell.cs
- src/library/DIPS.Mobile.UI/MemoryManagement/GarbageCollection.cs
We added in some versions ago that when adding to the FlatVisualChildrenList in CollectionContentTarget, they would remove their parent and disconnect its handler. This was because we saw that the memory leak propagated upwards, so if a component had a leak way inside the visual tree, all its parent controls (grandparents etc) would also leak. So with the Disconnecting of handler and removal of parent, we could contain the memory leak. 
However, when we change root, the current page is still displayed, and an animation occurs to change visually to the new root page. So, we tried to disconnect the handler while the page is still being displayed, that's why the app crashed. There is now put a delay of 2 seconds, so we avoid disconnecting the handler of the visible page.
> [MemoryLeak] Fixed crash of app when changing root page.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs
- src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetViewController.cs
- src/library/DIPS.Mobile.UI/Components/Shell/Shell.cs
- src/library/DIPS.Mobile.UI/MemoryManagement/CollectionContentTarget.cs
- src/library/DIPS.Mobile.UI/MemoryManagement/GCCollectionMonitor.cs
- src/library/DIPS.Mobile.UI/MemoryManagement/VisualTreeMemoryResolver.cs
I came upon a situation where a BottomSheet had memory leaks, but the BottomSheet itself were GC'ed. Thus, we could not traverse its VisualTree and resolve the memory leaks. Now I suggest that we auto resolve memory leaks before checking if there are any. Checking memory leaks before using the auto resolve did not offer much to us anyway.
Furthermore, I fixed duplicate checking of memory leaks in `BindingContext` of BottomSheets. Because now we do that when trying to resolve memory leaks for the BottomSheet view.
> [MemoryLeak] Will now try to resolve memory leaks before checking if there are any

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
- src/app/Playground/HåvardSamples/HåvardPageViewModel.cs
- src/app/Playground/Playground.csproj
- src/library/DIPS.Mobile.UI/Components/Labels/Android/MauiTextView.cs
- src/library/DIPS.Mobile.UI/Components/Labels/Label.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Labels/Label.cs
- src/library/DIPS.Mobile.UI/Components/Labels/iOS/MauiLabel.cs
There was an issue where changing `Text` after the label was truncated did not reflect. This was due to `Text` getting nullified when we use `FormattedText` from MAUI, which meant that the binding that consumers was doing did not trigger when it changes. Fixed this by introducing our own `Text`, which sets the MAUI `Text` property, and handles it being null + invalidate measure to make sure we re-truncate if needed.
> Fixed Label not showing its correct Text after truncation

- CHANGELOG.md
- src/app/MemoryLeakTests/App.xaml.cs
- src/app/MemoryLeakTests/Tests/NavigationTests.cs
- src/app/MemoryLeakTests/Tests/TestRegistrator.cs
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/iOS/ScrollPickerHandler.cs
After removing the `ChipHandler` in the previous PR, `Chip` is no longer a `UIButton`, thus, invoking a crash on iOS trying to convert `Chip` to a `UIButton`.
Additionally, I added some more memory leak testing for navigation
> [ScrollPicker][iOS] Fixed crash when trying to display scroll pickers.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/DateAndTimePicker.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/DatePicker.Properties.cs
For some reason, using the default date (01.01.0001) breaks the inline datepicker. It jumps forward two dates when selecting a date. Setting the default date to `DateTime.Now` fixes this issue.
> Set default date to `DateTime.Now` on datepickers to avoid a bug where the datepickers jumps two dates forward.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/API/Builder/iOS/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.cs
- src/library/DIPS.Mobile.UI/Components/Selection/iOS/SwitchHandler.cs
Designers complained that the SegmentedControl had too much height. This is because we set static height on the SegmentedControl, and additionally set padding. Instead, we should just use padding, and let maui calculate the height of the SegmentedControl based on font-size. This also has the benefit of scaling good with font-size changes.
On iOS, if the Switch was laid above another view that has a background color, the off state would blend in with the background color. With this fix, we set a static off color, so it will always be seen.
> Fixes for SegmentedControl and Switch on iOS

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonTypeStyle.cs
Just removed the padding, it had no effect anyways
> [Button][iOS] Fixed an issue where buttons with `IconButtonSmall` style would have a glitchy icon.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Buttons/ButtonsSamples.xaml
- src/app/Components/ComponentsSamples/ImageCapturing/ImageCaptureSample.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
[iOS] I found out that the Width/Height can be 0 (which we use to calculate the Corner Radius) if the button is inside a Grid that has IsVisible changed, with a * Row/Column definition. This is most likely a bug in MAUI, because the Width/Height is set on a later frame.
> [Button][iOS] Fixed an edge-case where some buttons did not get rounded corners.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/CapturedImage.cs
- src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/ImageCapture.ConfirmState.cs
- src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/ImageCapture.StreamingState.cs
It seems that when setting Translation on a view, on Android the pivot point does not take into account the translation. However, it does on iOS. A workaround for this is to wrap the image inside a grid, and translate the grid instead.
> [ImageCapture][Android] Fixed an issue where the rotated image would have wrong translation in either X or Y direction, when in edit mode.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreview.cs
* Fixed an issue on iOS where the tap to focus indicator were not placed correctly.
* Fixed an issue on Android where the tap to focus indicator were not animating. By placing the indicator inside a wrapper.
> [ImageCapture] Tap to focus indicator fixes

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreview.cs
Faced an unknown bug when using camera preview for a different use case than we have in our components app. Added try-catch-logging when we dispose to get rid of an app crash.
> Added try-catch and null point checks when we dispose the camera preview

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Chips/iOS/Chip.cs
- src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj
- src/library/DIPS.Mobile.UI/Effects/Layout/Android/LayoutPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Effects/Layout/iOS/LayoutPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Extensions/Markup/InvertedBoolExtension.cs
- src/library/DIPS.Mobile.UI/Extensions/Markup/StringCaseExtension.cs
- src/library/DIPS.Mobile.UI/Extensions/Markup/TimeSpanExtension.cs
Also tagged some MarkupExtensions with [AcceptEmptyServiceProvider].
Additionally, I enabled XC0045 warning to throw error. However, since we almost never use XAML, there was no errors to fix.
> Fixed a bug where toggled icon were always visible if a `Chip` was set to be toggleable and a crash bug with `Layout` effect

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs
> [ContextMenu] ContextMenu will now respect the property `IsEnabled`, if setting context menu on non-buttons.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs
When setting IsEnabled = false on ItemPicker when the page loads, the context menu would not respect it. But now it will!
> [iOS][ContextMenu] ContextMenu will now respect the property `IsEnabled` when the effect is attached to Element.

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/app/Playground/VetleSamples/TestBottomSheetNotFitToContent.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/Touch.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs
Very hard to reproduce. Previously we fixed a bug where the LongPressCommand were executed if you dismissed the ContextMenu at a perfect time, we fixed this by setting Touch.IsEnabled = false when opening the ContextMenu. However, this adds the Tap and LongPress delegates to the View, and if you have not set these Commands, you would get a very edge-case-crash when long pressing and then swiping down (In for example a BottomSheet).
In this PR I check if LongPressCommand is null, if it is, don't try to check if it can be executed.
> [ContextMenuEffect] Fixed edge-case-crash.

- CHANGELOG.md
- src/Directory.Packages.props
- src/app/Playground/Playground.csproj
- src/app/Playground/VetleSamples/TemplateSelector.cs
- src/app/Playground/VetleSamples/TimePlanningViewModel.cs
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/app/Playground/VetleSamples/VetlePageViewModel.cs
- src/app/Playground/VetleSamples/ViewCellTest.xaml
- src/library/DIPS.Mobile.UI/Components/Content/ContentControl.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/iOS/DateAndTimePickerService.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/Service/iOS/DatePickerService.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePickerShared/iOS/DateOrTimePickerPopoverViewController.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/TimePicker/iOS/TimePickerService.cs
- src/library/DIPS.Mobile.UI/Internal/Logging/DUILogService.cs
Additionally, we will now dismiss the datepicker popovers on iOS if the controls are disconnected.
> [ContentControl] Log and avoid possible crash if `BindingContext` and `SelectorItem` is the same object.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/Android/ExifOrientationExtensions.cs
When retrieving orientation from image data on image capture, there are some values that are not handled. We only really handle rotational orientation, so we just handle any other value than expected as default orientation.
> Make sure we handle unchecked orientation

- CHANGELOG.md
- src/app/Playground/VetleSamples/TemplateSelector.cs
- src/app/Playground/VetleSamples/TimePlanningViewModel.cs
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/ViewCellTest.xaml
- src/library/DIPS.Mobile.UI/API/Camera/Gallery/BottomSheet/GalleryBottomSheet.cs
- src/library/DIPS.Mobile.UI/API/Camera/Gallery/GalleryThumbnails.cs
- src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
- src/library/DIPS.Mobile.UI/Components/CheckBoxes/FilledCheckBox.cs
- src/library/DIPS.Mobile.UI/Components/ChipGroup/ChipGroup.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Android/OnToggledChangedListener.cs
- src/library/DIPS.Mobile.UI/Components/Images/Image/iOS/ImageHandler.cs
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/Android/ImageButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/iOS/ImageButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/LoadableListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/NavigationListItem.cs
- src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/NavigationMenuButton/NavigationMenuButton.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/DateAndTimePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/DatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableDateAndTimePicker/NullableDateAndTimePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableDatePicker/NullableDatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableDatePickerShared/BaseNullableDatePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/NullableTimePicker/NullableTimePicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/TimePicker/TimePicker.cs
- src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs
OnHandlerChanged can't be used, because it runs either when handler is attached or deattached. One must use OnHandlerChanging, and then check if the handler is null or not null. Otherwise, the mappers to the handler could be fired if changing some of the properties after handler is disconnected. Additionally, it saves some resources as the functions are being run when they don't need to.
> Make sure functions does not run when handler is null.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
OnHandlerChanging is run before the Handler is set, therefore we need to use OnHandlerChanged. I have no idea why this was implemented in the first place, it did not work
> [Button] Fixed an issue where if a button has bound to a property that returns false, the button would not change its style to disabled.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Buttons/Android/ButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Buttons/Android/MaterialButton.cs
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/Android/ImageButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/Android/ShapeableImageView.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/Android/MaterialScrollPickerFragment.cs
- src/library/DIPS.Mobile.UI/Extensions/Android/DoubleExtensions.cs
- src/library/DIPS.Mobile.UI/Extensions/Android/ViewExtensions.cs
From experience, setting Task.Delay inside a mapper function is bad practice, and have been one of the the leading cause of crashes in our library. Instead of setting Task.Delay in the mapper function, we instead override the OnDraw function. When this function is called, the hit rect is initialized and we can set the increased hit box size. This also has the benefit of updating the hit box size when ImageButton/Button's size is changed.
> [ImageButton][Button][Android] Fixed a rare crash when setting `AdditionalHitBoxSize`.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Buttons/Android/ButtonHandler.cs
For some reason, our QA got a crash when setting the foreground ripple on Button. The crash bug are not reproducible, however, I have try-catched and logged where the crash occurs, so that the app should no longer crash if the crash bug should resurface.
> [Button] Try-catched an unreproducible crash that happened in `ButtonHandler`.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Labels/Android/MauiTextView.cs
- src/library/DIPS.Mobile.UI/Components/Labels/iOS/MauiLabel.cs
Instead of `while(true)` I changed it to `while (modifiedOriginalText.Length > 0)`, to make sure substring will not take in a negative value. This happens if the TruncatedText has no space to display.
> [Label] Fixed a crash that could occur if `TruncatedText` is set, while `Label` has not enough width for the `TruncatedText` to display.

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
- src/app/Playground/MainPage.xaml
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchEffectLongPressGestureRecognizer.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchEffectTapGestureRecognizer.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs
- [Touch][iOS] Reinitialize the gesture to prevent it from loosing scroll capabilities on iOS 18.3.x.
> Prevent Touch from loosing scroll capabilities on iOS 18.3.x

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/TextFields/Editor/iOS/EditorHandler.cs
Default padding of a UITextView container is 8,0,8,0. When we made this component, we set this to UIEdgeInsets.Zero to make sure the text is not padded. So a Label and a Editor will always be placed at the same place. However, in later maui versions, this does not work correctly. It seems as though if an Editor have just enough space to display, the auto scroll functions in MAUI goes crazy and tries to make sure all the text is visible to the user. If we set the padding of UITextView to 1,0,1,0, this works correctly. 
I couldn't see that the 1,0,1,0 padding had any effect on how the Editor is displayed in MultiLineInputField and also dui:Editor.
This can also be reproduced by setting HeightRequest to a Editor from MAUI to a number where the text is slightly clipped, or just enough space …
> [Editor][iOS] Fixed an issue where the top of the page would sometimes scroll down if `dui:Editor` resides in a ScrollView/CollectionView.

- CHANGELOG.md
- src/app/Playground/HåvardSamples/HåvardPage.xaml
- src/app/Playground/MauiProgram.cs
- src/library/DIPS.Mobile.UI/API/Builder/DIPSUIOptions.cs
- src/library/DIPS.Mobile.UI/API/Builder/IDIPSUIOptions.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuEffect.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuLoggingMetadata.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/GlobalContextMenuClickMetadata.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.cs
SetContextMenuItemClickedCallback is now named ItemsShouldSendGlobalClicks.
The old implementation were too eager, and we want to opt in this feature by the consumer.
> [ContextMenu] Changes to SetContextMenuItemClickedCallback

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Android/ChipHandler.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Chip.Properties.cs
Don't know when this bug appeared, the mapper will run even though the value is not set. So it was set to zero.
> [Chip][Android] Fixed so that default CornerRadius will be set.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/iOS/CollectionViewHandler.cs
When we refactored how the padding worked in CollectionView, we needed to set corner radius on a element that actually received margin. With the other method, the cell itself got margin.
> [CollectionView][iOS] Fixed regression bug where `AutoCornerRadius` did not work.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/Touch.Properties.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/TouchPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/dotnet/TouchPlatformEffect.cs
- src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs
This is a regression bug from last PR, because now we listen to `IsEnabled` property changes on the Element, and then remove gestures when it's disabled. We need to also animate it to original opacity if this is the case.
> [Touch][iOS] Fixed a bug where disabling an element right after touch effect fires, makes the element stay at clicked opacity.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Converters/ValueConverters/TypeToObjectConverter.cs
- src/tests/unittests/Converters/ValueConverters/TypeToObjectConverterTests.cs
Added IncludeInheritance property to TypeToObjectConverter to allow for checks against sub-types. Introduced this property as to not break the existing behaviour.
> Added IncludeInheritance property to TypeToObjectConverter to allow to check for sub-types

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/InLineContent/InLineContentOptions.cs
Made a change in last PR where InlineContentOptions is only set if InlineContent is set, but consumers uses InlineContentOptions without setting InlineContent sometimes to make sure the title is filled out.
> [ListItem] Fixed a regression bug where consumers could not fill out title without setting `InlineContent`.

- CHANGELOG.md
- src/app/Playground/VetleSamples/TextHighlighter.cs
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
Was reproduced by creating a ListItem from scratch, noticed that setting RowDefinitions="*", made the bug appear.
> [ListItem][iOS] Fixed a bug where setting `FormattedText` sometimes did not wrap on a new line.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuGroup.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuSeparatorItem.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/IContextMenuItem.cs
- src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
For a long time we have had a bug where the Menu would not change even though the binding has changed itself. This is because we set the menu of the button only at the start, or if the ItemsSource changes. This is not reproducible on `LongPressed` mode, because the menu is built when the animation starts. 
Now we check in PropertyChanged if any properties of `ContextMenuItem` changes, if so, rebuild the menu.
> [ContextMenu][iOS] ContextMenu's with mode `Pressed` will now rebuild the menu when one of the items' properties changes. 

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamplesViewModel.cs
- src/app/Playground/EirikSamples/EirikPage.xaml
- src/app/Playground/EirikSamples/EirikPageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
Item pickers will now support people selecting a custom item, using text from the search bar. The `FreeItemTextFactory` property must be set for this to be enabled, as well as `Mode=BottomSheet` and `BottomSheetConfiguration.HasSearch=true`. The factory must be a `Func<string, object>` delegate that returns an object of the same type as `ItemsSource` and `SelectedItem`. The string parameter is the user's text input.
Additionally, a prefix can be shown for the item in the bottom sheet, by setting the `FreeTextPrefix`. The format of the resulting text will be `<FreeTextPrefix><UserInput>`.
> [ItemPicker] Added `FreeTextItemFactory` and `FreeTextPrefix` properties to support custom text item in bottom sheet mode

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
It was because the item was at first index after all has been added. Now we add em all in one swoop
> [ItemPicker] Fixed an issue where keyboard would close if searching with free-text enabled.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/iOS/CollectionViewHandler.cs
What happened was that in the cached list of cells, we tried updating the first and last cell to accomodate new elements added to the list, but we didnt check if it was the same cell. If it is the same cell, there is no need to update corner radius.
> [CollectionView][iOS] Fixed bug where auto corner radius in grouped collectionview would sometimes be set wrong.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.cs
On Android it only works if HorizontalOptions is set on ScrollView
> [SegmentedControl][Android] Fixed bug where setting `HorizontalOptions` had no effect.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamplesViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/BottomSheetPickerConfiguration.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPickerBottomSheet.cs
You can now set `FooterTemplate` to `BottomSheetPickerConfiguration` to add footer content to the bottom sheet's internal `CollectionView`.
> Added `FooterTemplate` property to `BottomSheetPickerConfiguration` to allow for setting a footer to item picker bottom sheet.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamplesViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPicker.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPicker.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPickerBottomSheet.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/ResetBehaviour.cs
- src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
- src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.en.resx
- src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx
Added a `ResetBehaviour` property to `MultiItemsPicker`. Setting this property will display a "Reset"-button at the bottom of the picker's bottom sheet. This button will by default clear all selected items. The `ResetBehaviour.Command` property can be set to override how the list should be modified when the button is pressed.
> Added `ResetBehaviour` property to `MultiItemsPicker` to enable a button for resetting selected items

- CHANGELOG.md
- src/app/Playground/MauiProgram.cs
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs
iOS default sets the cancel button to disabled if search bar loses focus. We do not want this to happen.
> [SearchBar][iOS] Keep cancel button enabled when losing focus on search bar.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/BarcodeScanResultView.xaml
Somehow, turning off additional space fixes the freeze. The additional spacing functions correctly everywhere else. This is a quick fix to make it not freeze. We should look into why it happens at a later time
> [iOS] Fixed freeze when showing barcode result.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
Problem: When searching in the item picker for bottom sheet, the result items are duplicated
Resolution: The matching items were added twice to the filteredItems, so removed one of the add lines
> [ItemPickerBottomSheet]Fix duplicates when filtering in itempicker bottomsheet

- CHANGELOG.md
- src/app/Playground/VetleSamples/BottomSheetWithToolbar.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
For better consistency with iOS
> [BottomSheet][Android] Focusing `SearchBar` will now expand the `BottomSheet`.

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/app/Playground/VetleSamples/VetlePageViewModel.cs
- src/library/DIPS.Mobile.UI/Components/Images/Image/Android/ImageHandler.cs
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/iOS/IconTintColorHandler.cs
This PR addresses issues with image tint colors persisting incorrectly due to view recycling in both iOS and Android UI components.
iOS: Resets the image’s rendering mode to UIImageRenderingMode.AlwaysOriginal and clears TintColor when no tint is specified, preventing leftover tint colors from recycled image views.
Android: Clears the color filter using ClearColorFilter() when no tint color is provided, ensuring recycled views don’t retain previous tint colors.
By properly resetting tint states during view reuse, this update prevents visual artifacts and ensures consistent UI appearance when images are reused in lists or other recycled views.
> [CollectionView][Image] Handle resetting image tint colors on iOS and Android to avoid tint artifacts caused by view recycling.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/API/Camera/Gallery/ImageThumbnailView/ImageThumbnailView.cs
Problem: Close button on an image were placed inside of the image instead of on the corner on iOS
Solution: Remove the Margin
> [ImageThumbnailView] Fix position of close button on image

- CHANGELOG.md
- src/app/Playground/VetleSamples/BottomSheetWithToolbar.xaml
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
- src/library/DIPS.Mobile.UI/Extensions/ViewExtensions.cs
In previous related PR, we only made sure to expand the BottomSheet if the searchbar that is internal in the BottomSheet was focused. Now we expand it if any searchbar inside bottomsheet is focused.
> [BottomSheet][Android] Focusing any `SearchBar` in `BottomSheet` will now expand the `BottomSheet`.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPickerBottomSheet.cs
Additionally, `SearchBar` inside `BottomSheet` now has keyboard `Done` button as default.
> [MultiItemsPicker] Can now tap outside the `BottomSheet` to close.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Counters/CountersSamples.xaml
- src/app/Components/ComponentsSamples/Counters/CountersSamples.xaml.cs
- src/app/Components/ComponentsSamples/Counters/CountersSamplesViewModel.cs
- src/app/Components/REGISTER_YOUR_SAMPLES_HERE.cs
- src/library/DIPS.Mobile.UI/AssemblyInfo.cs
- src/library/DIPS.Mobile.UI/Components/Counters/Counter.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Counters/Counter.cs
- src/library/DIPS.Mobile.UI/Components/Counters/CounterDisplayMode.cs
Added a `Counter` component for having an easy way to display an in-line counter. Supports an optional secondary value, and both primary and secondary values can be shown with an urgent style.
> Add `Counter` component

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
- src/app/Playground/VetleSamples/CollectionViewTests/GroupedCollectionView2.xaml
- src/app/Playground/VetleSamples/SegmentedControl.xaml
- src/app/Playground/VetleSamples/SegmentedControl.xaml.cs
- src/app/Playground/VetleSamples/TextHighlighter.cs
- src/app/Playground/VetleSamples/TextHighlighterConverter.cs
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Buttons/ButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Buttons/iOS/ButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Android/ChipHandler.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Chip.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Chips/Chip.cs
- src/library/DIPS.Mobile.UI/Components/Chips/iOS/Chip.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs
- src/library/DIPS.Mobile.UI/Components/Shell/Shell.cs
Additionally, added so that ItemPicker can take in `AdditionalContextMenuItem`, to for example navigate to a page in the same context menu.
Also fixed a bug on Android where the CustomIconTintColor were not applied. Furthermore, removed all dividers in the navigationbar on shell pages on iOS.
> [ItemPicker] Added `Large` size, which will transform its layout.

- CHANGELOG.md
- src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamples.xaml
- src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamples.xaml.cs
- src/library/DIPS.Mobile.UI/API/Builder/AppHostBuilderExtensions.cs
- src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.cs
- src/library/DIPS.Mobile.UI/Effects/Animation/Animation.Properties.cs
- src/library/DIPS.Mobile.UI/Effects/Animation/Effects/ScaleInEffect.cs
- src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertTypeStyle.cs
- [AlertView] Fixed icon tint colors not being set.
- [AlertView] Fixed icon size.
- [AlertView] Now using correct text style on title, if the description is not set.
- [AlertView] Can now be easily animated.
- [Animations] Added Scale animation.
> `AlertView` can now be easily animated, and fixed some bugs

- CHANGELOG.md
- src/app/Playground/Playground.csproj
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Buttons/iOS/ButtonHandler.cs
- src/library/DIPS.Mobile.UI/Components/Images/ImageButton/iOS/IconTintColorHandler.cs
Workaround for bug: https://github.com/dotnet/maui/pull/25107
> [Button] Fixed bug where toggling IsVisible would reset icon's tint color.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/CheckmarkListItem.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Icon/IconOptions.Properties.cs
- src/library/DIPS.Mobile.UI/Components/ListItems/Options/Icon/IconOptions.cs
- src/library/DIPS.Mobile.UI/Components/Selection/Checkmark.cs
Fix bug where checkmark and checkmark in checkmarklistitem is never visible on iOS by changing Opacity instead of TintColor when IsSelected changes.
> use opacity instead of tintcolor to toggle checkmark

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Tag/Tag.cs
When tag has no icon, column spacing was still applied to the tag, making the margin on the left of the tab too big. Therefore applied margin right to the icon, instead of using column spacing.
> [Tag] Fix wrong margin on tag without icon

- CHANGELOG.md
- src/app/Playground/VetleSamples/VetlePage.xaml
- src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPickerBottomSheet.cs
- src/library/DIPS.Mobile.UI/Components/TextFields/Editor/Editor.cs
If the footer was not set, this would be shown:
> [Android][MultiItemsPicker] Fixed issue where ToString of the MultiItemsPicker would be visible if footer on the BottomSheet were not set.

- CHANGELOG.md
- src/Directory.Packages.props
- src/app/Components/ComponentsSamples/Chips/ChipsSamples.xaml
- src/library/DIPS.Mobile.UI/API/Camera/Shared/Android/CameraFragment.cs
Skiasharp and the camera packages did not support 16kb page sizes, they are now updated to do so.
For more information: https://developer.android.com/guide/practices/page-sizes
TL;DR: Android 16 only uses 16kb page sizes for apps (Use more memory, better performance etc). We have to support 16kb page sizes to be able to deploy to Android 16 devices.
> [Android] Update nuget packages to support 16kb page sizes.

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Components/Loading/LoadingOverlay/LoadingOverlay.Properties.cs
- src/library/DIPS.Mobile.UI/Components/Loading/LoadingOverlay/LoadingOverlay.cs
In certain cases LoadingOverlay Text and ContentFadeOutValue did not work since Handler on LoadingOverlay was null when initializing
> Fixed LoadingOverlay creation when handler is null

- CHANGELOG.md
- src/library/DIPS.Mobile.UI/Converters/ValueConverters/InvertedBoolConverter.cs
- src/tests/unittests/Converters/ValueConverters/InvertedBoolConverterTests.cs
If the consumer sends a null value to the converter, it threw an exception and the app crashed. Nullable bools is not great, but the converter should handle it.
> InvertedBoolConverter now supports nullable bools.
