src/library/DIPS.Mobile.UI.Droid/Components/BottomSheets/BottomSheetFragment.cs
src/library/DIPS.Mobile.UI.iOS/Components/Searching/SearchBarRenderer.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.Properties.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/Picker.Mode.BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/Picker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/Picker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/PickerBottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/SelectableItem.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
src/samples/DIPS.Mobile.UI.Samples.Droid/MainActivity.cs
src/samples/DIPS.Mobile.UI.Samples/Components/Pickers/PickersSamples.xaml
src/samples/DIPS.Mobile.UI.Samples/Components/Searching/SearchBarSamples.xaml
src/samples/DIPS.Mobile.UI.Samples/SampleData/SampleDataStorage.cs

Added search bar to picker when mode is set to bottom sheet. This can be disabled by setting HasSearchBar = false

Added search bar to picker when mode is set to bottom sheet. 

---

src/library/DIPS.Mobile.UI.iOS/Components/BottomSheets/BottomSheetContentPage.cs
src/library/DIPS.Mobile.UI.iOS/Components/ContextMenus/ContextMenuButtonRenderer.cs
src/library/DIPS.Mobile.UI.iOS/Components/ContextMenus/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI.iOS/Components/Searching/SearchBarRenderer.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.Properties.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.cs
src/library/DIPS.Mobile.UI/Components/Pickers/Picker.Mode.BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/PickerBottomSheet.cs
src/samples/DIPS.Mobile.UI.Samples/Components/BottomSheets/Sheets/ListInBottomSheet.xaml
src/samples/DIPS.Mobile.UI.Samples/Components/BottomSheets/Sheets/SimpleBottomSheet.xaml
src/samples/DIPS.Mobile.UI.Samples/Components/ContextMenu/ContextMenuSamples.xaml
src/samples/DIPS.Mobile.UI.Samples/Components/Pickers/PickersSamples.xaml
src/samples/DIPS.Mobile.UI.Samples/Components/Pickers/PickersSamples.xaml.cs

- Cleaned up code
- Made sure we guard against iOS 15 features for the bottom sheet.
- Made sure Context Menu on iOS does not use subtitles (iOS 16 feature)
- Bug fix for searching in a bottom sheet mode picker

Cleaned up code and minor bugfixes

---

src/library/DIPS.Mobile.UI.Droid/Components/BottomSheets/BottomSheetFragment.cs
src/samples/DIPS.Mobile.UI.Samples.Droid/MainActivity.cs

Made sure bottom sheet is secure flags if activity flags is set to secure

---

CHANGELOG.md
src/app/Components/ComponentsSamples/BottomSheets/Sheets/SimpleBottomSheet.xaml
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs

[BottomSheet] The content on android is now centered

---

CHANGELOG.md
build/BuildSystem/dotnet/dotnet.csx
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/app/Components/Platforms/iOS/Info.plist
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.no.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Components/Resources/Raw/appconfig.json
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.Properties.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/IContextMenu.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs

- Context Menu: Fixed a bug where context menus sometimes does not show on iOS.
- Context Menu: Fixed issue where checking items did not work as expected for both platforms.
- Components app: Made sure the Android app is signed.

Improvements to Context Menu

---

CHANGELOG.md
src/app/Components/MainPage.cs
src/app/Components/ResourcesSamples/Sizes/SizesSamples.xaml.cs
src/app/Components/SamplesPage.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetContentPage.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Android/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
src/library/DIPS.Mobile.UI/Components/CheckBoxes/CheckBox.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView.cs
src/library/DIPS.Mobile.UI/Components/Lists/VerticalStackLayout.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/Android/DateAndTimePickerHandler.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
src/library/DIPS.Mobile.UI/Extensions/Android/ViewExtensions.cs
src/library/DIPS.Mobile.UI/GlobalUsings.cs
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/colors.xml
src/library/DIPS.Mobile.UI/Resources/Colors/ColorName.cs
src/library/DIPS.Mobile.UI/Resources/Colors/Colors.xaml
src/library/DIPS.Mobile.UI/Resources/Icons/IconName.cs
src/library/DIPS.Mobile.UI/Resources/Icons/Icons.xaml
src/library/DIPS.Mobile.UI/Resources/Sizes/CornerRadiusExtension.cs
src/library/DIPS.Mobile.UI/Resources/Sizes/SizeName.cs
src/library/DIPS.Mobile.UI/Resources/Sizes/Sizes.xaml
src/library/DIPS.Mobile.UI/Resources/Sizes/Sizes.xaml.cs
src/library/DIPS.Mobile.UI/Resources/Sizes/SizesExtension.cs
src/library/DIPS.Mobile.UI/Resources/Sizes/ThicknessExtension.cs

- Added new colors from design system
- Changed Sizes namespace

Added new Colors from design system

---

src/library/DIPS.Mobile.UI/Components/Content/ContentControl.Properties.cs
src/library/DIPS.Mobile.UI/Components/Content/ContentControl.cs

splitted properties to its own file

---

src/app/Components/Components.csproj
src/app/Components/Platforms/iOS/Info.plist
src/app/Playground/Platforms/iOS/Info.plist
src/app/Playground/Playground.csproj

Fixed deploying to device on iOS for Intellij Rider

---

CHANGELOG.md
build/BuildSystem/dotnet/dotnet.csx
build/bootstrapper/bootstrapper.sh
build/build.csx
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/HorizontalInlineDatePicker.cs

- Made sure that HorizontalInlineDatePicker do not crash when you change date.
- [ComponentsApp] Made sure the correct version of gets set to the iOS app.

Made sure that HorizontalInlineDatePicker do not crash when you change date.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/colors.xml
src/library/DIPS.Mobile.UI/Resources/Colors/ColorName.cs
src/library/DIPS.Mobile.UI/Resources/Colors/Colors.xaml
src/library/DIPS.Mobile.UI/Resources/Icons/IconName.cs
src/library/DIPS.Mobile.UI/Resources/Icons/Icons.xaml
src/library/DIPS.Mobile.UI/Resources/Sizes/SizeName.cs
src/library/DIPS.Mobile.UI/Resources/Sizes/Sizes.xaml

Here is the latest resources that was generated by DIPS.Mobile.DesignTokens repository

Resources was updated from DIPS.Mobile.DesignTokens

---

build/BuildSystem/Versioning/VersionUtil.csx
build/build.csx
src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
src/app/Components/Resources/Raw/appconfig.json
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.cs
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj

added option to add custom view to navigationlistitem

---

CHANGELOG.md
src/app/Components/ResourcesSamples/Sizes/SizesAsFontSize.xaml.cs
src/app/Components/ResourcesSamples/Sizes/SizesAsVisualBoxes.xaml.cs
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/Android/MaterialDatePickerFragment.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/HorizontalInLine/HorizontalInlineDatePicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/Service/iOS/DatePickerBottomSheet.cs

Fixed an issue with ios Inline date pickers width being too small.

---

CHANGELOG.md
build/BuildSystem/dotnet/dotnet.csx

made sure nuget uses release configuration of the library

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/NavigationMenuButton/NavigationMenuButton.cs
src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/themes.xml

Fixed an issue where touch effect were not displayed on some devices

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/Alerting/AlertingSamples.xaml
src/app/Components/ComponentsSamples/Alerting/Dialogs/DialogSamples.xaml
src/app/Components/ComponentsSamples/Alerting/Dialogs/DialogSamples.xaml.cs
src/app/Components/ComponentsSamples/Alerting/Dialogs/DialogSamplesViewModel.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetleTestPage1.xaml.cs
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/AlertDialog.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/DialogService.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/DialogService.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/dotnet/DialogService.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/iOS/DialogService.cs
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.nb.resx
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx

Added Dialogs and fixed LocalizedStrings issue in library

---

CHANGELOG.md
build/BuildSystem/dotnet/dotnet.csx

fixed changelog versions to correspond with nuget

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Alerting/Dialogs/DialogSamples.xaml
src/app/Components/ComponentsSamples/Alerting/Dialogs/DialogSamplesViewModel.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/iOS/DialogService.cs

[iOS] Fixed an issue when displaying two dialogs concurrently

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/app/Playground/VetleSamples/VetleTestPage1.xaml.cs
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage2.xaml
src/app/Playground/VetleSamples/VetleTestPage2.xaml.cs
src/library/DIPS.Mobile.UI/API/Builder/Android/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/API/Builder/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/Components/Navigation/DUINavigationPage.cs
src/library/DIPS.Mobile.UI/Components/Toolbars/Android/DUIToolbar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Toolbars/Android/DUIToolbar.cs
src/library/DIPS.Mobile.UI/Components/Toolbars/Android/DUIToolbarHandler.cs
src/library/DIPS.Mobile.UI/Effects/Modal/Android/ModalPlatformEffect.cs
src/library/DIPS.Mobile.UI/Effects/Modal/Modal.Properties.cs
src/library/DIPS.Mobile.UI/Effects/Modal/Modal.cs

[Android] Added a workaround to enable toolbar for modal pages

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuHelper.cs

- Icons on a context menu item is now of type icon image source.

Icons on a context menu item is now of type icon image source.

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/Alerting/AlertingSamples.xaml
src/app/Components/ComponentsSamples/BottomSheets/BottomSheetSamples.xaml
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
src/app/Components/ComponentsSamples/Loading/LoadingSamples.xaml
src/app/Components/ComponentsSamples/Navigation/NavigationSamples.xaml
src/app/Components/ComponentsSamples/Pickers/PickersSample.xaml
src/app/Components/ComponentsSamples/Searching/SearchingSamples.xaml
src/app/Components/MainPage.cs
src/app/Components/SamplesPage.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView.cs

- [ListItem] Changed default value of corner radius

[ListItem] Changed default value of corner radius

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/library/DIPS.Mobile.UI/Components/Lists/IndicatorView.cs
src/library/DIPS.Mobile.UI/Components/Loading/RefreshView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Loading/RefreshView.cs

- Added IndicatorView.
- Made sure RefreshView is wrapping the content in a Grid to fix : https://github.com/dotnet/maui/issues/7315 on dotnet 7.

Added IndicatorView and fixed issue with refreshview

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/Android/ImageButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/Android/REMOVE_WHEN_BUG_FIXED.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/ImageButton.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/ImageButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/dotnet/ImageButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/iOS/ImageButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Loading/RefreshView.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/NavigationMenuButton/NavigationMenuButton.cs

[Android] dui:ImageButton now fixes padding issue: https://github.com/dotnet/maui/pull/14905

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Checkboxes/CheckboxesSample.xaml
src/app/Components/ComponentsSamples/Checkboxes/CheckboxesSampleViewModel.cs
src/app/Components/ComponentsSamples/Saving/SaveViewSamples.xaml
src/app/Components/ComponentsSamples/Saving/SaveViewSamples.xaml.cs
src/app/Components/ComponentsSamples/Saving/SaveViewSamplesViewModel.cs
src/app/Components/ComponentsSamples/Saving/SavingSamples.xaml
src/app/Components/ComponentsSamples/Saving/SavingSamples.xaml.cs
src/app/Components/REGISTER_YOUR_SAMPLES_HERE.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/CheckBoxes/FilledCheckBox.Properties.cs
src/library/DIPS.Mobile.UI/Components/CheckBoxes/FilledCheckBox.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentSavePage/ContentSavePage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentSavePage/ContentSavePage.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs

- Added SaveView
- Added FilledCheckBox
- Added ContentSavePage
- ListItem can now take in a Command and a CommandParameter

Moved SaveView

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.cs

Extended ListItem to be able to contain a vertical content item

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
src/app/Components/ComponentsSamples/ListItems/ListItemsSamplesViewModel.cs
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/LoadableListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/LoadableListItem.cs
src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs

- [Android] Fixed visual bug with dui:Touch.IsEnabled
- Added LoadableListItem

Added LoadableListItem

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.Properties.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs

Fixed bug where ItemPicker ItemsSource would not update itself

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/LoadableListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/LoadableListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.cs

Moved Icon Property from NavigationListItem to ListItem

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ResourcesSamples/Icons/IconBottomSheet.xaml
src/app/Components/ResourcesSamples/Icons/IconBottomSheet.xaml.cs
src/app/Components/ResourcesSamples/Icons/IconsSamples.xaml
src/app/Components/ResourcesSamples/Icons/IconsSamples.xaml.cs
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/library/DIPS.Mobile.UI/API/Library/DUI.cs
src/library/DIPS.Mobile.UI/Components/Images/Image/Image.Properties.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonService.cs

Rollback FlationActionButton removal 

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/SomeKindaBottomSheet.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/NavigationListItem.cs

- [ListItem] Added the ability to set the icons visibility.
- [ListItem] Changed inheritance from ContentView to Border for consumers to modify the shape and colors of the list item.
- [ComponentsApp] Cleaned up List Items page.

Changes to ListItem for more flexibility for consumers.

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/ListItems/ListItemsSamples.xaml
src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
src/app/Components/ComponentsSamples/Pickers/ItemPickersSamplesViewModel.cs
src/app/Components/ComponentsSamples/Pickers/PickersSample.xaml
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/SelectableListItem.cs

Added custom selectable picker item

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/ListItems/LoadableListItem.cs

Fixed bug where content would not expand when setting static content item on LoadableListItem.

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs

[ListItem] Subtitle will now react to property change

[ListItem] Subtitle will now react to property change 

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/HåvardSamples/HåvardPageViewModel.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/iOS/DUIDatePicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs

fixed an issue with item picker and horizontalinlinedatepicker

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/API/Builder/Android/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/Components/Lists/Android/CollectionViewHandler.cs
src/library/DIPS.Mobile.UI/Components/Lists/Android/MauiRecyclerView.cs

Fixed a bug on Android where if you set ItemSpacing on a CollectionView, the CollectionView tries to snap to the elements.

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/library/DIPS.Mobile.UI/Components/Labels/Android/MauiTextView.cs
src/library/DIPS.Mobile.UI/Components/Labels/iOS/MauiLabel.cs

Fixed a bug where setting FormattedText on dui:Label would crash the application

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/library/DIPS.Mobile.UI/Components/Labels/Android/MauiTextView.cs

Fixed a bug where setting IsEllipzised property were not set correctly when in a CollectionView

---

build/build.csx

added animations to buildscript

---

CHANGELOG.md
build/build.csx
src/app/Components/ComponentsSamples/Chips/ChipsSamples.xaml
src/app/Components/ComponentsSamples/Chips/ChipsSamples.xaml.cs
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/library/DIPS.Mobile.UI/Components/Chips/iOS/ChipHandler.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs

- [Chip] Made sure background color of chip is set correctly.
- [Components app] Made sure samples includes closable chip

[Chip][iOS] Fix for background colour

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

fixed app crash for iOS Search bar

---

build/BuildSystem/DesignTokens/DesignTokenApplier.csx
build/build.csx

Made sure android colors does not update when it doesn't have to.

Made sure android colors does not update when it doesn't have to.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/app/Playground/VetleSamples/VetleTestPage1.xaml.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs

Added new property to SearchPage: CancelCommand

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/CheckBoxes/FilledCheckBox.Properties.cs
src/library/DIPS.Mobile.UI/Components/CheckBoxes/FilledCheckBox.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/CheckmarkListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/CheckmarkListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/RadioButtonListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/RadioButtonListItem.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs
src/library/DIPS.Mobile.UI/Components/Selection/Checkmark.Properties.cs
src/library/DIPS.Mobile.UI/Components/Selection/Checkmark.cs
src/library/DIPS.Mobile.UI/Components/Selection/ISelectable.cs
src/library/DIPS.Mobile.UI/Components/Selection/RadioButton.Properties.cs
src/library/DIPS.Mobile.UI/Components/Selection/RadioButton.cs

Added haptics when people select items or save

Added haptics when people select items or save

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/RadioButtonListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/MultiItemsPicker/MultiItemsPickerBottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.cs
src/library/DIPS.Mobile.UI/Components/Sorting/SortControl.Properties.cs
src/library/DIPS.Mobile.UI/Components/Sorting/SortControlBottomSheet.cs
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/styles.xml

- [ItemPicker] Added haptics for when people select a item from ItemPicker with context menu mode.
- [SortControl] Added haptics for when people select a sort option.
- [SegmentedControl] Added haptics for when people select/deselect a segment from the segmented control.

added more haptics to sortcontrol, segmentedcontrol and item picker

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Buttons/ButtonsSamples.xaml
src/app/Components/ComponentsSamples/Buttons/ButtonsSamples.xaml.cs
src/app/Components/ComponentsSamples/Selection/SelectionSamples.xaml
src/app/Components/REGISTER_YOUR_SAMPLES_HERE.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/library/DIPS.Mobile.UI/Components/Buttons/Android/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Button.Properties.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
src/library/DIPS.Mobile.UI/Components/Buttons/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Buttons/dotnet/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Buttons/iOS/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonDefaultStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonStyleResources.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonTypeStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Chip/ChipStyleResources.cs
src/library/DIPS.Mobile.UI/Resources/Styles/StylesExtension.cs

Added Buttons

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/iOS/ImageButtonHandler.cs

Fixed an issue where app would crash trying to set tint color on ImageButton when using hot reload

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs

Made sure people can tap the right side of the screen.

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPageViewModel.cs
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs
src/library/DIPS.Mobile.UI/Components/Selection/Switch.cs

- Made sure SaveView uses correct vibration.
- Made sure Switch takes less space on Android.

Small UX improvements to Switch and SaveView

---

CHANGELOG.md
src/app/Playground/App.xaml.cs
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/Android/ImageButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/ImageButton.cs

…ped for Android
[ImageButton] Made sure ImageButton padding is correctly set when IsVisible is flipped for Android

[ImageButton] Made sure ImageButton padding is correctly set when IsVisible is flipped for Android

---

CHANGELOG.md
src/app/Playground/App.xaml.cs
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs

Made property 'IsChecked' bindable in ContextMenuItem

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.LongPressed.cs

Added 'IsVisible' property to ContextMenuItem

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/Buttons/ButtonsSamples.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
src/library/DIPS.Mobile.UI/Components/Images/ImageButton/ImageButton.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonStyleResources.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonTypeStyle.cs

- [Button][Styles] Added PrimaryRoundedSmall/Large
- [Button][Styles] Added SecondaryRoundedSmall/Large
- [Button][Styles] Added GhostRoundedSmall/Large

Added rounded buttons style and changed default disabled colors on buttons

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonTypeStyle.cs

changed the default color of disabled buttons

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuEffect.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/ContextMenu/ContextMenuOptions.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/ContextMenu/ContextMenuOptions.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/Android/FloatingNavigationButtonHandler.cs
src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs
src/library/DIPS.Mobile.UI/Effects/Touch/Touch.cs

Added ContextMenuOptions on ListItem

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuHelper.cs

Added 'IsDestructive' property on ContextMenuItem

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/CheckmarkListItem.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/CheckmarkListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/RadioButtonListItem.Properties.cs

Modified 'CheckmarkListItem' so that changing IsSelected does not fire SelectedCommand

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.cs

[Android] Keyboard will now close when navigating from a searchbar

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.LongPressed.cs

[iOS] Possible fix for crash when using long press context menu

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/AlertDialog.cs
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.cs

Fixed a bug with dialog on android and a bug in SegmentedControl

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchEffectGestureRecognizerDelegate.cs
src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchEffectTapGestureRecognizer.cs
src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs

Fixed bugs with touch API

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuHelper.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.Properties.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenu.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuItem.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuSeparatorItem.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/IContextMenu.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/IContextMenuItem.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuHelper.cs

Added support for dividers in context menu

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs

Fixed a bug where items inside ListItem were sometimes not tappable

---

CHANGELOG.md
src/app/Components/ComponentsSamples/TextFields/EntrySamples.xaml
src/app/Components/ComponentsSamples/TextFields/EntrySamples.xaml.cs
src/app/Components/ComponentsSamples/TextFields/TextFieldsSamples.xaml
src/app/Components/ComponentsSamples/TextFields/TextFieldsSamples.xaml.cs
src/app/Components/REGISTER_YOUR_SAMPLES_HERE.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/API/Builder/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Android/EntryHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry.cs
src/library/DIPS.Mobile.UI/Components/TextFields/EntryHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/dotnet/EntryHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/iOS/EntryHandler.cs

Added new control: 'Entry'

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Chips/iOS/ChipHandler.cs

Fix toggle icon margins

---

build/bootstrapper/bootstrapper.sh

Do not exit bootstrapper if not on macOS

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.targets

Increased icons base size

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.targets

reset base size changes on icons

---

CHANGELOG.md
src/app/Components/ResourcesSamples/Icons/IconsSamples.xaml
src/library/DIPS.Mobile.UI/Components/Images/Image/Image.Properties.cs

Reverted change where color on Image were default set

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.cs

Changed default dui:ContentPage background color

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/HåvardSamples/HåvardPageViewModel.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/Android/CollectionViewHandler.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/CollectionView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/CollectionViewHandler.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/dotnet/CollectionViewHandler.cs
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/iOS/CollectionViewHandler.cs

Added `ReloadData` to `CollectionView`

Added `ReloadData` to `CollectionView`

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.cs

Added `TextColor` and `Style` properties to `SubtitleOptions`

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/HåvardSamples/HåvardPage2.xaml
src/app/Playground/HåvardSamples/HåvardPage2.xaml.cs
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

Im proved SearchBar / Page focusing flexibility.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs

Now you might actually see the difference when using DividersOptions :D

Fixed two small bugs with ListItem

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
src/library/DIPS.Mobile.UI/Components/Searching/dotnet/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

- [SearchBar] Made it possible to Focus and Unfocus
- [SearchBar] Made sure consumers can set `Text` property.

Searchbar focus improvements.

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardBottomSheet.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomBarFragment.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetFragment.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.Properties.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Positioning.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/dotnet/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetService.cs
src/library/DIPS.Mobile.UI/Exceptions/Only_Here_For_UnitTests.cs

- [BottomSheet] Added BottomBarButtons, to add floating buttons to the bottom of the bottom sheet.

Added BottomBarButtons, to add floating buttons to the bottom of the bottom sheet.

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardBottomSheet.xaml
src/app/Playground/HåvardSamples/HåvardPageViewModel.cs
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/InLineContent/InLineContentOptions.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/InLineContent/InLineContentOptions.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Editor/Android/EditorHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Editor/EditorHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Editor/iOS/EditorHandler.cs

Added new option to InLineContentOptions, bug fixes

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Sorting/SortControl.cs

Moved the sort icon to the left side of the text in SortControl

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.cs

Added MaxWidth to ListItem.TitleOptions

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardBottomSheet.xaml
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.cs

- [MultiLineInputField] Added CancelCommand.
- [MultiLineInputField] Added Save and Cancel tapped events.

MultiLineInputField - Added CancelCommand and events

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs

Fixed an issue where floating navigation button would go out of bounds when changing orientation

---

CHANGELOG.md
src/app/Playground/App.xaml.cs
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/app/Playground/VetleSamples/VetleTestPage1.xaml.cs
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonConfigurator.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonService.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/IFloatingNavigationButtonConfigurator.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.cs

Added new property to ContentPage: 'ShouldHideFloatingNavigationMenuButton'

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/TextFields/Editor/Editor.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/Entry.cs

Make sure dui:Editor and dui:Entry capitalizes each new sentence.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Searching/SearchPageSamples.xaml
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
src/library/DIPS.Mobile.UI/Components/Searching/dotnet/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/Android/EntryHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/Entry.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/iOS/EntryHandler.cs

Introduced two new properties on SearchBar. Bugfixes

---

build/build.csx

Removed signing from build script as its now added as tasks in pipeline azure

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/Buttons/iOS/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButton.cs

Fixed bug with floating navigation button and one where buttons only had an icon

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.Properties.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheetService.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs

Added new property: 'ShouldAutoFocusSearchBar' for BottomSheet and ItemPicker. 

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

added un focused event to search bar

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
src/library/DIPS.Mobile.UI/Components/Chips/iOS/ChipHandler.cs

Ensure chip resizes when selected item changes.

---

CHANGELOG.md
src/app/Playground/EirikSamples/EirikPage.xaml
src/app/Playground/EirikSamples/EirikPage.xaml.cs
src/app/Playground/EirikSamples/EirikPage2.xaml
src/app/Playground/EirikSamples/EirikPage2.xaml.cs
src/app/Playground/EirikSamples/EirikPageViewModel.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/ContextMenus/ContextMenuEffect.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

Fixed Context Menu data context not getting updated in collections that are updated from another page

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Loading/LoadingSamples.xaml
src/app/Components/ComponentsSamples/Loading/StateView/StateViewSamples.xaml
src/app/Components/ComponentsSamples/Loading/StateView/StateViewSamples.xaml.cs
src/app/Components/ComponentsSamples/Loading/StateView/StateViewSamplesViewModel.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.nb.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/DefaultView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/DefaultViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/EmptyView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/EmptyViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/ErrorView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/ErrorViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/IStateChangedAware.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/LoadingView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/LoadingViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/State.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateViewModel.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.nb.resx
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx

Added StateView

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/library/DIPS.Mobile.UI/Components/Alerting/SystemMessage/SystemMessage.cs

Removed animation from SystemMessage on Android

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Loading/StateView/StateViewSamples.xaml
src/app/Components/ComponentsSamples/Loading/StateView/StateViewSamplesViewModel.cs
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/Labels/iOS/MauiLabel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/IStateChangedAware.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/State.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateViewModel.cs

[BreakingChange] [StateView] ViewModel is now in charge of creating 'StateViewModel', added new property: 'ShouldUpdateViewWhenStateSetToSame'

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.cs

added gc logging

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/app/Playground/VetleSamples/VetleTestPage1.xaml.cs
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/DefaultViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/EmptyView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/EmptyViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/ErrorView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/ErrorViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/IRefreshAbleViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/IRefreshableViewModel.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateView.cs
src/library/DIPS.Mobile.UI/Components/Loading/StateView/StateViewModel.cs

[BreakingChange][StateView] Added the ability for consumer to add a RefreshView to some state views.

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/HåvardSamples/HåvardPage3.xaml
src/app/Playground/HåvardSamples/HåvardPage3.xaml.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs
src/library/DIPS.Mobile.UI/Effects/Touch/iOS/TouchPlatformEffect.cs

Fixed memory leaks for Touch and Context Menu effects.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.cs

[ListItem] Added `MaxLines` and `LineBreakMode` to subtitle

---

CHANGELOG.md
src/app/MemoryLeakTests/App.xaml
src/app/MemoryLeakTests/MauiProgram.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.Properties.cs

Bumped changelog and added bindable for profiling

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs

Added `FooterView` to `SearchPage`

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Effects/Layout/Android/LayoutPlatformEffect.cs

[Android] Added null check to `CornerRadius` effect. 

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentSavePage/ContentSavePage.cs

Fixed an issue where several `SaveView`'s in `ContentSavePage` could potentially be created.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/app/Playground/VetleSamples/VetleTestPage1ViewModel.cs
src/library/DIPS.Mobile.UI/API/Builder/Android/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/Components/Pages/Android/ContentPageHandler.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContentPage.cs

[Android] Fixed an issue where icons were black in modal pages.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
src/library/DIPS.Mobile.UI/Components/Pickers/BottomSheetPickerConfiguration.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs

Allow title for picker with mode=bottomsheet

---

CHANGELOG.md
global.json
src/global.json
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj

Pin dotnet SDK and MAUI version

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/iOS/BarcodeScanner.cs
src/library/DIPS.Mobile.UI/API/Camera/iOS/PreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/iOS/UITapToFocusGestureRecognizer.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.nb.resx
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx

- Added pinch to zoom
- Improved tap to focus
- Improved recommended zoom factor for people
- Tilgjengelighet: Lagt til bedre voice over for å justere zoom med slider

Improved iOS Barcode scanner

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/API/Camera/Android/PreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/Android/BarcodeScanner.cs
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/BarcodeScanner.cs

- Added zoom slider for barcode scanner for Android.

Added zoom slider for barcode scanner for Android.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/BarcodeScanning/BarcodeScanningSample.xaml
src/app/Components/ComponentsSamples/BarcodeScanning/BarcodeScanningSample.xaml.cs
src/library/DIPS.Mobile.UI/API/Builder/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/Android/BarcodeScanner.cs
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/BarcodeScanResult.cs
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/BarcodeScanner.cs
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/iOS/BarcodeScanner.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/Android/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreview.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/dotnet/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/iOS/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/iOS/UITapToFocusGestureRecognizer.cs
src/library/DIPS.Mobile.UI/API/Camera/PreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/dotnet/PreviewHandler.cs
src/library/DIPS.Mobile.UI/AssemblyInfo.cs

Renamed `Preview` to `CameraPreview`

---

CHANGELOG.md
src/app/Components/ComponentsSamples/BarcodeScanning/BarcodeScanningSample.xaml
src/app/Components/ComponentsSamples/BarcodeScanning/BarcodeScanningSample.xaml.cs
src/app/Components/ComponentsSamples/Tip/TipSamples.xaml
src/app/Components/ComponentsSamples/Tip/TipSamples.xaml.cs
src/app/Components/REGISTER_YOUR_SAMPLES_HERE.cs
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/Platforms/iOS/Program.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/API/Camera/BarcodeScanning/Android/BarcodeScanner.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/Android/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreview.Properties.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreview.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/dotnet/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/iOS/CameraPreviewHandler.cs
src/library/DIPS.Mobile.UI/API/Tip/Android/TipService.cs
src/library/DIPS.Mobile.UI/API/Tip/TipCommand.cs
src/library/DIPS.Mobile.UI/API/Tip/TipService.cs
src/library/DIPS.Mobile.UI/API/Tip/dotnet/TipService.cs
src/library/DIPS.Mobile.UI/API/Tip/iOS/TipService.cs
src/library/DIPS.Mobile.UI/API/Tip/iOS/TipUIPopoverPresentationControllerDelegate.cs
src/library/DIPS.Mobile.UI/API/Tip/iOS/TipUIViewController.cs
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/Shell/Android/ShellRenderer.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/SingleLineInputField.cs
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj

For å la folk enkelt gi et tips om funksjonalitet er det utviklet en `TipService` som kan brukes. Denne er pr. nå avhengig av at du har noe i siden din som den kan feste seg til (`anchorView`).
API for å bruke dette:
```csharp
TipService.Show("My awesome tip", Label, 4000);
```
[Wiki for hva dette er og hvordan du bruker det.](https://github.com/DIPSAS/DIPS.Mobile.UI/wiki/Providing-help-in-your-app)
Jeg har også gjort det mulig å fortelle CameraPreview at man skal ha et tip for zooming. Det er i tillegg mulig å hente ut en boolean verdi for om folk har brukt zoom eller ikke.

Added TipService

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/ScrollPickerViewModel.cs

Handle IScrollPickerComponent(s) being null

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.Properties.cs
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Subtitle/SubtitleOptions.cs

Added 'FormattedText' to Subtitle in `ListItem`.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Chips/ChipsSamples.xaml
src/app/Components/ComponentsSamples/Chips/ChipsSamplesViewModel.cs
src/library/DIPS.Mobile.UI/Components/ChipGroup/ChipGroup.Properties.cs
src/library/DIPS.Mobile.UI/Components/ChipGroup/ChipGroup.cs

ChipGroup changes

---

CHANGELOG.md
src/Directory.Packages.props

Bump MAUI NuGet packages to 8.0.20

Bumped MAUI to 8.0.20

---

CHANGELOG.md
src/Directory.Packages.props

Revert MAUI bump to 8.0.20

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Pickers/ItemPickersSamples.xaml
src/app/Components/ComponentsSamples/Pickers/ItemPickersSamplesViewModel.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/iOS/ContextMenuPlatformEffect.Pressed.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.Mode.ContextMenu.cs

[ItemPicker] Fixed an issue where the context menu did not reflect correctly what item was selected when setting selected item programatically.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/API/Tip/iOS/TipService.cs
src/library/DIPS.Mobile.UI/Extensions/ViewExtensions.cs

Made sure tip can be opened inside bottom sheet ios

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Pickers/DateTimePickerSamplesViewModel.cs
src/app/Components/ComponentsSamples/Pickers/DateTimePickersSamples.xaml
src/app/Components/ComponentsSamples/Pickers/ScrollPickerSamplesViewModel.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableDateAndTimePicker/NullableDateAndTimePicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableDateAndTimePicker/NullableDateAndTimePicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableDatePicker/NullableDatePicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableDatePicker/NullableDatePicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableDatePickerShared/BaseNullableDatePicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableTimePicker/NullableTimePicker.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/NullableTimePicker/NullableTimePicker.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/Component/IScrollPickerComponent.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/iOS/ScrollPickerHandler.cs

Changes to `ScrollPicker` and `NullableDatePickers`

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Pickers/DateTimePickerSamplesViewModel.cs
src/app/Components/ComponentsSamples/Pickers/DateTimePickersSamples.xaml
src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/Android/DateAndTimePickerHandler.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/iOS/DateAndTimePickerHandler.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/Android/MaterialDatePickerFragment.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/iOS/DatePickerHandler.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePickerShared/iOS/DateTimeToNSDateExtensions.cs

- [DatePicker][iOS] Made sure IgnoreLocalTime is respected.
- [DateAndTimePicker][Android] Made sure IgnoreLocalTime is respected.

Made sure date pickers respect ignorelocaltime

---

CHANGELOG.md
src/app/Playground/HåvardSamples/HåvardPage.xaml
src/app/Playground/HåvardSamples/HåvardPage.xaml.cs
src/app/Playground/Playground.csproj
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj

`SavingText` is now bindable for `SaveView`

`SavingText` is now bindable for `SaveView`

---

build/BuildSystem/Git.csx

fixed build

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs

[SaveView] Made sure SaveView SavingText is bindable.

[SaveView] Made sure SaveView SavingText is bindable.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.Properties.cs
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.SingleMode.cs

[SegmentedControl] Added property `ShouldDeSelectOnSameItemTapped`.

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/TextHighlighterConverter.cs
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/ListItems/ListItem.cs
src/library/DIPS.Mobile.UI/Components/VirtualListView/Android/RvScrollListener.cs
src/library/DIPS.Mobile.UI/Components/VirtualListView/Controls/VirtualListView.cs

[ListItem] ListItem and VirtualListView bugfixes

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/library/DIPS.Mobile.UI/Components/Shell/iOS/ShellRenderer.cs

[iOS][ContextMenuToolbarItem] Fixed an issue where `IsCheckable` did not work.

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/BottomSheets/Sheets/BottomSheetWithToolbar.xaml
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.Properties.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/dotnet/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetViewController.cs

[BottomSheet] Added property 'BackButtonBehavior', so that the back button can be set in a bottomsheet.

---

CHANGELOG.md
src/app/Playground/Playground.csproj
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DateAndTimePicker/Android/DateAndTimePickerHandler.cs

[Android] Bug fixes on DateAndTimePicker

---

CHANGELOG.md
src/app/Playground/VetleSamples/BottomSheetWithToolbar.xaml
src/app/Playground/VetleSamples/BottomSheetWithToolbarViewModel.cs
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.Properties.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheet.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/dotnet/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetViewController.cs

Added property to set visibility of the back button.
I tried to use BackButtonBehaviour's property `IsVisible´, but I could not for the life of me make PropertyChanged get called.

[BottomSheet] Added property `IsBackButtonVisible`.

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/Alerting/AlertingSamples.xaml
src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamples.xaml
src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamples.xaml.cs
src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamplesViewModel.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.Designer.cs
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.en.resx
src/app/Components/Resources/LocalizedStrings/LocalizedStrings.resx
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.cs
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj
src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertStyleResources.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertTypeStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Styles.cs
src/library/DIPS.Mobile.UI/Resources/Styles/StylesExtension.cs

- [AlertView] Added alert view. A new component to use in line when you need to alert people using your app.

Added AlertView

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertTypeStyle.cs

Updated icons for AlertView

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertTypeStyle.cs

Corrected icons for AlertView

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Resources/Styles/Alert/AlertTypeStyle.cs

[AlertView] Corrected icon for Error style.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/Android/FloatingNavigationButtonService.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonService.cs
src/library/DIPS.Mobile.UI/Resources/Icons/Icons.cs

Fixed icons and added more logging to FAB

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Navigation/FloatingNavigationButtonSamples.xaml.cs

Exception handling of floating navigation menu

---

src/app/Components/Components.csproj
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/Android/FloatingNavigationButtonService.cs

Added potential problems with FloatingNavigationMenu crashing sporadically on Android

---

CHANGELOG.md
src/app/Components/MauiProgram.cs
src/library/DIPS.Mobile.UI/API/Library/DUI.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/Android/FloatingNavigationButtonService.cs
src/library/DIPS.Mobile.UI/Components/Navigation/FloatingNavigationButton/FloatingNavigationButtonService.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/Android/MaterialScrollPickerFragment.cs
src/library/DIPS.Mobile.UI/Components/Pickers/ScrollPicker/iOS/ScrollPickerHandler.cs
src/library/DIPS.Mobile.UI/Internal/Logging/Android/DUILogService.cs
src/library/DIPS.Mobile.UI/Internal/Logging/DUILogService.cs
src/library/DIPS.Mobile.UI/Internal/Logging/dotnet/DUILogService.cs
src/library/DIPS.Mobile.UI/Internal/Logging/iOS/DUILogService.cs

- Added DUILogService that should be used internally so it's easier to understand what's going on. Log levels are Debug and Error. Debug is only visible while debugging for now.

Added internal logging

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamples.xaml
src/app/Components/ComponentsSamples/ContextMenus/ContextMenuSamplesViewModel.cs
src/library/DIPS.Mobile.UI/Components/Pages/ContextMenuToolbarItem.cs

[ContextMenuToolbarItem] Bindings for Context Menu Items now works.

[ContextMenuToolbarItem] Bindings for Context Menu Items now works.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/MemoryManagement/GCCollectionMonitor.cs
src/library/DIPS.Mobile.UI/MemoryManagement/IgnoreMemoryLeakAttachedProperty.cs

[MemoryLeak] Added a bindable attached property so that consumers can ignore memory leak resolving on certain views/pages.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/TextFields/MultiLineTextArea/MultiLineInputFieldSamples.xaml
src/app/Components/ComponentsSamples/TextFields/MultiLineTextArea/MultiLineInputFieldSamples.xaml.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.en.resx
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx

[MultiLineInputField] Add `MaxTextLength` property.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs

[Button] Made sure to guard changing style if platformview is null.

---

src/library/DIPS.Mobile.UI/Effects/Touch/Android/TouchPlatformEffect.cs

[Touch] Removed default contentdescription

---

CHANGELOG.md
src/app/Components/ComponentsSamples/ImageCapturing/ImageCaptureSample.xaml.cs
src/library/DIPS.Mobile.UI/API/Camera/Gallery/BottomSheet/GalleryBottomSheet.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/ImageCapture.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/Settings/ImageCaptureSettings.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/Views/BottomToolbar/ConfirmState/ConfirmStateView.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/Views/TopToolbar/ImageCaptureTopToolbarView.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.Designer.cs
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.en.resx
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx

ImageCapture changes

---

CHANGELOG.md
build/bootstrapper/bootstrapper.sh
src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj

Will now localize text correctly.

---

build/bootstrapper/bootstrapper.sh

made sure we run 15.4

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/API/Camera/Gallery/ImageThumbnailView/ImageThumbnailView.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs
src/library/DIPS.Mobile.UI/Components/Buttons/iOS/ButtonHandler.cs

[ImageCapture][iOS] Fixed close button on thumbnail

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Buttons/ButtonsSamples.xaml
src/app/Components/ComponentsSamples/ImageCapturing/ImageCaptureSample.xaml
src/library/DIPS.Mobile.UI/API/Camera/Gallery/BottomSheet/GalleryBottomSheet.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/ImageCapture.ConfirmState.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/ImageCapture.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/Views/BottomToolbar/EditState/EditStateBottomView.cs
src/library/DIPS.Mobile.UI/API/Camera/ImageCapturing/Views/TopToolbar/ImageCaptureTopToolbarView.cs
src/library/DIPS.Mobile.UI/API/Camera/Preview/CameraPreview.cs

Top toolbar will now have 1/3 of the height of bottom toolbar.

[ImageCapture] Fixed toolbar height on smaller devices.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPicker.cs

[ItemPicker] Ensure `IsEnabled` is respected

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/CheckBoxes/FilledCheckBox.Properties.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Saving/SaveView/SaveView.cs

[SaveView] You can now change the opacity of the non-checked animation

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/DialogService.cs

[Android] Fix crash when trying to display dialog while app minimized.

---

CHANGELOG.md
src/app/Components/App.xaml.cs
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/DialogService.cs

[Android] Fix crash when trying to remove dialog while app minimized.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/DialogService.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/DialogService.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/dotnet/DialogService.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/iOS/DialogService.cs

[DialogService] You can now determine if the dialogserice is showing a dialog

[DialogService] You can now determine if the dialogserice is showing a dialog

---

CHANGELOG.md
build/bootstrapper/bootstrapper.sh

Use xCode 16.1

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Labels/Android/MauiTextView.cs

[Label][Android] Error handle when trying to set ellipsis text.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Effects/Layout/iOS/LayoutPlatformEffect.cs

[iOS][Layout] Fix crash.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/TextFields/MultiLineTextArea/MultiLineInputFieldSamples.xaml
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/SingleLineInputField.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/SingleLineInputField.cs

Improvements to Single/MultiInputField

---

CHANGELOG.md
src/app/Components/ComponentsSamples/TextFields/MultiLineTextArea/MultiLineInputFieldSamples.xaml
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/MultiLineInputField/MultiLineInputField.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/SingleLineInputField.Properties.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/SingleLineInputField.cs

Improvements to Single/MultiInputField (#519)

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs

IsEnabled property is set when Handler is set.

Button's that are disabled as default will now have the disabled style.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.en.resx
src/library/DIPS.Mobile.UI/Resources/LocalizedStrings/LocalizedStrings/DUILocalizedStrings.resx

[Localization] Swapped language of three properties in DUILocalizedStrings.

---

src/library/DIPS.Mobile.UI/DIPS.Mobile.UI.csproj

treat XC0103 warning as error

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Buttons/Android/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Buttons/Button.cs

[Button][Android] Touch effect on buttons will not go out of bounds anymore.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.Properties.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.cs

Ensure icon is placed correctly according to whether `Title` is set or not

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/themes.xml

[Android15] Opts out of edge-to-edge to fix layout issues.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/API/Builder/iOS/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/EntryHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/iOS/EntryHandler.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/iOS/MauiDoneAccessoryView.cs
src/library/DIPS.Mobile.UI/Components/TextFields/Entry/iOS/TryFixCrashEntryHandler.cs

Also, hopefully fixed a crash. Based on this discussion: https://github.com/xamarin/xamarin-macios/issues/21648, it seems that a lot of people have the same issue as us, and some resolved it by doing what I have done in this PR.

[Entry][iOS] Added 'Done' toolbar item.

---

build/BuildSystem/DesignTokens/DesignTokenApplier.csx
build/BuildSystem/Helpers/WriteToFileHelper.csx
build/build.csx

Make sure to await functions in build script where you write to files, to make sure the program does not exit before the writing is finished

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Resources/Sizes/SizesExtension.cs

[Sizes] Convert size to int if BindableProperty expects an int.

---

CHANGELOG.md
src/app/Playground/VetleSamples/TestBottomSheetFitToContent.xaml
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/Android/CollectionViewHandler.cs

[CollectionView][Android] Fix bug where `AutoCornerRadius` would apply to header and footer.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Searching/SearchPageSamples.xaml
src/library/DIPS.Mobile.UI/Components/Pickers/ItemPicker/ItemPickerBottomSheet.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs

[SearchPage][ItemPicker] Fixed so that items will get correct default margin and corner radius

---

CHANGELOG.md
src/app/Components/Components.csproj
src/app/Components/ComponentsSamples/Searching/SearchBarSamples.xaml
src/app/Components/ComponentsSamples/Searching/SearchPageSamples.xaml
src/app/Playground/SanderSamples/SanderPage.xaml
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
src/library/DIPS.Mobile.UI/Components/Searching/dotnet/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

Added property `IsAutocorrectEnabled` for SearchBar and SearchPage

---

src/app/Components/Components.csproj

Add android as target framework to components app

---

CHANGELOG.md
src/app/Components/ComponentsSamples/AmplitudeView/AmplitudeViewSamples.xaml
src/app/Components/ComponentsSamples/AmplitudeView/AmplitudeViewSamples.xaml.cs
src/app/Components/REGISTER_YOUR_SAMPLES_HERE.cs
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePageViewModel.cs
src/library/DIPS.Mobile.UI/AssemblyInfo.cs
src/library/DIPS.Mobile.UI/Components/VoiceVisualizer/AmplitudeView.Properties.cs
src/library/DIPS.Mobile.UI/Components/VoiceVisualizer/AmplitudeView.cs
src/library/DIPS.Mobile.UI/Components/VoiceVisualizer/AmplitudeViewController.cs
src/library/DIPS.Mobile.UI/Components/VoiceVisualizer/AmplitudeViewDrawable.cs

https://github.com/DIPSAS/DIPS.Mobile.UI/wiki/AmplitudeView

Added AmplitudeView

---

CHANGELOG.md
src/app/Playground/MainPage.xaml
src/app/Playground/VetleSamples/CollectionViewTests/GroupedCollectionView.xaml
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/Android/CollectionViewHandler.cs
src/library/DIPS.Mobile.UI/Components/VoiceVisualizer/AmplitudeView.cs
src/library/DIPS.Mobile.UI/Components/VoiceVisualizer/AmplitudeViewController.cs

Additionally fixed bug where pause animation on timer could be set multiple times on AmplitudeView.
Furthermore, added ElapsedMilliseconds to Controller in AmplitudeView.

[CollectionView][Android] Fixed a bug where CornerRadius and padding were not set on last element if group footer was not set.

---

CHANGELOG.md
src/app/Playground/VetleSamples/CollectionViewTests/RegularCollectionView.xaml
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/iOS/CollectionViewHandler.cs

[CollectionView][iOS] Support Border as root element for padding.

---

CHANGELOG.md
src/app/Components/App.xaml.cs
src/app/Playground/App.xaml.cs
src/app/Playground/TestTab.xaml
src/app/Playground/TestTab.xaml.cs
src/library/DIPS.Mobile.UI/API/TabBadge/TabBadgeService.cs
src/library/DIPS.Mobile.UI/Components/Shell/Android/ShellRenderer.cs
src/library/DIPS.Mobile.UI/Components/Shell/iOS/ShellRenderer.cs

With this API, you can now set badge on tabs

Added `TabBadgeService`.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Lists/CollectionView/CollectionView.cs

Fix bug when list is small, and its bouncing. Would jitter list

[iOS][CollapsibleElement] Fix bug when small list.

---

CHANGELOG.md
src/app/Playground/VetleSamples/TestBottomSheetFitToContent.xaml
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Android/BottomSheetHandler.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/Header/BottomSheetHeader.cs
src/library/DIPS.Mobile.UI/Components/BottomSheets/iOS/BottomSheetViewController.cs

Did not disconnect the handlers that is not part of maui layout

[BottomSheet] Fixed memory leak.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetlePage.xaml.cs
src/library/DIPS.Mobile.UI/Components/TextFields/InputFields/SingleLineInputField.cs

[SingleLineInputField] Make sure to set InputView visible when text is set from consumer.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Tags/TagsSamples.xaml
src/library/DIPS.Mobile.UI/Components/ListItems/Extensions/NavigationListItem.cs
src/library/DIPS.Mobile.UI/Components/Shell/Shell.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Tag/TagStyle.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Tag/TagStyleResources.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Tag/TagTypeStyle.cs

Additionally:
- [NavigationListItem] Removed default icon color and set chevron color.
- [TabBar] Set different background color.

[Tag] Add `Information` style.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/app/Playground/VetleSamples/VetleTestPage1.xaml
src/library/DIPS.Mobile.UI/Components/Pickers/SegmentedControl/SegmentedControl.cs

[SegmentedControl][Android] Make sure all border always have same height.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Counters/CountersSamples.xaml
src/app/Components/ComponentsSamples/Counters/CountersSamplesViewModel.cs
src/library/DIPS.Mobile.UI/Components/Counters/Counter.Properties.cs
src/library/DIPS.Mobile.UI/Components/Counters/Counter.cs

[Counter] Add `IsError` and `IsSecondaryError` properties

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/API/Builder/Android/AppHostBuilderExtensions.cs
src/library/DIPS.Mobile.UI/API/Library/Android/DUI.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Dialog/Android/DialogFragment.cs
src/library/DIPS.Mobile.UI/Components/ContextMenus/Android/ContextMenuPlatformEffect.cs
src/library/DIPS.Mobile.UI/Components/Loading/ActivityIndicator.cs
src/library/DIPS.Mobile.UI/Components/Loading/Android/ActivityIndicator.cs
src/library/DIPS.Mobile.UI/Components/Loading/Android/ActivityIndicatorHandler.cs
src/library/DIPS.Mobile.UI/Components/Pickers/DatePicker/Android/MaterialDatePickerFragment.cs
src/library/DIPS.Mobile.UI/Components/Searching/Android/IndeterminateProgressBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/Android/IndeterminateProgressBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/Android/InternalSearchBar.cs
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchPage.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Selection/Android/SwitchHandler.cs
src/library/DIPS.Mobile.UI/Components/Shell/Android/ShellRenderer.cs
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/styles.xml
src/library/DIPS.Mobile.UI/Platforms/Android/Resources/values/themes.xml

* Removed custom styling of dialogs.
* Set `elevationOverlayEnabled` to false, to ensure true colors.
* Now using switch from material 3
* Now using ProgressBar from material 3
* Changed styling of SearchBar
* Renamed iOSSearchFieldBackgroundColor -> SearchFieldBackgroundColor
* Modified VerticalOffset of Badge

Upgraded to material design 3.

---

CHANGELOG.md
src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamples.xaml
src/app/Components/ComponentsSamples/Alerting/Alerts/AlertSamplesViewModel.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertView.cs
src/library/DIPS.Mobile.UI/Components/Alerting/Alert/AlertViewService.cs

Added `AlertViewService` to easily trigger `AlertView` animation.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/BottomSheets/Header/BottomSheetHeader.cs
src/library/DIPS.Mobile.UI/Resources/Styles/Button/ButtonTypeStyle.cs

Changed some colors

---

CHANGELOG.md
src/app/Playground/TestTab.xaml
src/app/Playground/TestTab.xaml.cs
src/library/DIPS.Mobile.UI/Components/Shell/Android/ShellRenderer.cs

[Android] Retapping tab will now pop to root, similar to iOS.

---

CHANGELOG.md
src/app/Playground/VetleSamples/VetlePage.xaml
src/library/DIPS.Mobile.UI/Components/Searching/Android/SearchBarHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/SearchBar.Properties.cs
src/library/DIPS.Mobile.UI/Components/Searching/iOS/SearchBarHandler.cs

[SearchBar] Updated styling.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/Buttons/iOS/ButtonHandler.cs
src/library/DIPS.Mobile.UI/Components/Searching/Android/IndeterminateProgressBar.Properties.cs

[Button][iOS] Fix possible crash.

---

CHANGELOG.md
src/library/DIPS.Mobile.UI/Components/ListItems/Options/Title/TitleOptions.Properties.cs

add comment on LineBreakMode, used in listitem

Add comment to LineBreakMode Property
